src/core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('manager/', include('recipemanager.urls')),
    path('admin/', admin.site.urls),
]

src/recipemanager/urls.py
from django.urls import path

from . import views

app_name = 'recipemanager'

urlpatterns = [
    path('', views.index, name='index'),
    path('ingredient/', views.ingredient_list, name='ingredient_list'),
    path('ingredient/list/', views.ingredient_list, name='ingredient_list'),
    path('ingredient/create/', views.ingredient_create, name='ingredient_create'),
    path('ingredient/<str:ingredient_id>/edit/', views.ingredient_edit,
         name='ingredient_edit'),
    path('ingredient/<str:ingredient_id>/confirm_delete/', views.ingredient_confirm_delete,
         name='ingredient_confirm_delete'),
    path('ingredient/<str:ingredient_id>/delete/', views.ingredient_delete,
         name='ingredient_delete'),

    path('recipe/', views.recipe_list, name='recipe_list'),
    path('recipe/list/', views.recipe_list, name='recipe_list'),
    path('recipe/create/', views.recipe_create, name='recipe_create'),
    path('recipe/<str:recipe_id>/view/', views.recipe_view,
         name='recipe_view'),
    path('recipe/<str:recipe_id>/edit/', views.recipe_edit,
         name='recipe_edit'),
    path('recipe/<str:recipe_id>/delete/', views.recipe_delete,
         name='recipe_delete'),
]

src/recipemanager/models.py
from django.db import models


class Ingredient(models.Model):
    ean = models.CharField(max_length=13, primary_key=True)
    name = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    price = models.DecimalField(max_digits=100, decimal_places=2)
    unit = models.CharField(max_length=10)

class Recipe(models.Model):
    name = models.CharField(max_length=100)
    cost = models.DecimalField(max_digits=100, decimal_places=2)

class RecipeListing(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    ingredient_quantity = models.DecimalField(max_digits=100, decimal_places=2)

src/recipemanager/controllers.py
from django.http import HttpResponse
from django.shortcuts import render
from django.db.models import Q
from .models import Ingredient, Recipe, RecipeListing
import collections
import json

def ingredient_already_exists(ean, name):
    if len(Ingredient.objects.filter(Q(ean=ean) | Q(name=name))):
        return True
    else:
        return False

def parse_ingredient_form_data(request, model):
    model_fields = [f.attname for f in model._meta.fields]
    parsed_form_data = dict()
    for field in request.POST:
        if field in model_fields:
            parsed_form_data[field] = request.POST[field]
    return parsed_form_data

def update_recipe_cost(recipe):
    listings = RecipeListing.objects.filter(recipe=recipe)
    recipe_cost = 0
    for l in listings:
        recipe_cost += l.ingredient_quantity / l.ingredient.amount * l.ingredient.price
    recipe.cost = recipe_cost
    recipe.save()

def chain_ingredient_update(updated_ingredient):
    listings = RecipeListing.objects.filter(ingredient=updated_ingredient)
    recipes = set()
    for l in listings:
        recipes.add(l.recipe)

    for r in recipes:
        update_recipe_cost(r)

def render_homepage(request):
    return render(request, 'recipemanager/home.html')


class IngredientManager():
    def list(request):
        ingredients = Ingredient.objects.all()
        return render(request, 'recipemanager/ingredient_list.html', {'ingredients': ingredients})

    def create(request):
        if request.method == 'GET':
            return render(request, 'recipemanager/ingredient_create.html')
        elif request.method == 'POST':
            parsed_form_data = parse_ingredient_form_data(request, Ingredient)
            try:
                if ingredient_already_exists(parsed_form_data['ean'], parsed_form_data['name']):
                    return_payload = {
                        'error': 'name and/or ean already taken',
                        'form_data': parsed_form_data
                    }
                    return render(request, 'recipemanager/ingredient_create.html', return_payload)

                Ingredient(**parsed_form_data).save()
            except Exception as exp:
                return HttpResponse(status=500)

            success_msg = {'success': 'Ingredient created!'}
            return render(request, 'recipemanager/ingredient_create.html', success_msg)

    def edit(request, ingredient_id):
        if request.method == 'GET':
            ingredient = Ingredient.objects.filter(ean=ingredient_id)[0]
            return render(request, 'recipemanager/ingredient_edit.html', {'form_data': ingredient})
        elif request.method == 'POST':
            parsed_form_data = parse_ingredient_form_data(request, Ingredient)
            ingredient = Ingredient.objects.filter(ean=ingredient_id)[0]
            updated_fields = 0
            for field, form_value in parsed_form_data.items():
                if str(ingredient.__getattribute__(field)) != form_value:
                    setattr(ingredient, field, form_value)
                    updated_fields += 1
            ingredient.save()
            chain_ingredient_update(ingredient)
            if updated_fields:
                return render(request, 'recipemanager/ingredient_edit.html', {'success': 'Ingredient updated!'})
            else:
                return render(request, 'recipemanager/ingredient_edit.html', {'success': 'Nothing changed!'})

    def confirm_delete(request, ingredient_id):
        ingredient = Ingredient.objects.filter(ean=ingredient_id)[0]
        listings = RecipeListing.objects.filter(ingredient=ingredient)
        return render(request, 'recipemanager/ingredient_confirm_delete.html',
                {'ingredient': ingredient, 'listings': listings})

    def delete(request, ingredient_id):
        ingredient = Ingredient.objects.filter(ean=ingredient_id)[0]
        listings = RecipeListing.objects.filter(ingredient=ingredient)
        for l in listings:
            l.recipe.cost -= l.ingredient_quantity / l.ingredient.amount * l.ingredient.price
            l.recipe.save()
            l.delete()
        try:
            ingredient.delete()
            chain_ingredient_update(ingredient)
            return render(request, 'recipemanager/ingredient_delete.html', {
                'success': 'Sucessfully deleted ingredient #%s.' % ingredient_id})
        except Exception as exp:
            return render(request, 'recipemanager/ingredient_delete.html')

def form2structured_data(posted_data):
    recipe_eans = list()
    for field in posted_data:
        if field[:20] == 'ingredient-selected-':
            recipe_eans.append(field[20:])

    recipe_ingredients = list()
    ean2quantity = dict()
    recipe_cost = 0
    for ean in recipe_eans:
        ingredient = Ingredient.objects.filter(ean=ean)[0]
        recipe_ingredients.append(ingredient)
        curr_quantity = float(posted_data['%s-item-quantity' % ean])
        ean2quantity[ean] = curr_quantity
        recipe_cost += curr_quantity/float(ingredient.amount)*float(ingredient.price)

    return {
        'recipe_ingredients': recipe_ingredients,
        'recipe_cost': recipe_cost,
        'ean2quantity': ean2quantity
    }

class RecipeManager():
    def list(request):
        recipes = Recipe.objects.all()
        return render(request, 'recipemanager/recipe_list.html', {'recipes': recipes})

    def create(request):
        if request.method == 'GET':
            ingredients = Ingredient.objects.all()
            return render(request, 'recipemanager/recipe_create.html', {'ingredients': ingredients})
        if request.method == 'POST':
            data = form2structured_data(request.POST)

            recipe = Recipe(name=request.POST['name'], cost=data['recipe_cost'])
            recipe.save()

            for ingredient in data['recipe_ingredients']:
                listing = RecipeListing(recipe=recipe,
                                        ingredient=ingredient,
                                        ingredient_quantity=data['ean2quantity'][ingredient.ean])
                listing.save()

            success_msg = 'Successfully created recipe #%s: %s.' % (recipe.id, recipe.name)
            return render(
                    request, 'recipemanager/recipe_create.html', {'success': success_msg})

    def view(request, recipe_id):
        recipe = Recipe.objects.filter(id=recipe_id)[0]
        listings = RecipeListing.objects.filter(recipe=recipe)
        for l in listings:
            l.unit_cost = l.ingredient_quantity / l.ingredient.amount * l.ingredient.price
        return render(request, 'recipemanager/recipe_view.html',
                      {'recipe': recipe, 'listings': listings})

    def edit(request, recipe_id):
        if request.method == 'GET':
            recipe = Recipe.objects.filter(id=recipe_id)[0]
            listings  = {
                l.ingredient.ean: l.ingredient_quantity
                for l in RecipeListing.objects.filter(recipe=recipe)
            }
            ingredients = Ingredient.objects.all()
            for i in ingredients:
                if i.ean in listings:
                    i.curr_recipe_quantity = listings[i.ean]
            payload =  {
                'form_data': recipe,
                'listings': listings,
                'ingredients': ingredients
            }
            return render(request, 'recipemanager/recipe_edit.html', payload)

        elif request.method == 'POST':
            data = form2structured_data(request.POST)
            ean2form_data = {i.ean: i for i in data['recipe_ingredients']}
            recipe = Recipe.objects.filter(id=recipe_id)[0]
            listings = RecipeListing.objects.filter(recipe=recipe)
            ean2listings = {l.ingredient.ean: l for l in listings}

            for ean in set(list(ean2form_data.keys()) + list(ean2listings.keys())):
                if ean in ean2form_data and ean in ean2listings:
                    form_quantity = data['ean2quantity'][ean]
                    db_quantity = ean2listings[ean].ingredient_quantity
                    if form_quantity != db_quantity:
                        ean2listings[ean].ingredient_quantity = form_quantity
                        ean2listings[ean].save()
                if ean in ean2form_data and ean not in ean2listings:
                    new_listing = RecipeListing(recipe=recipe,
                                        ingredient=ean2form_data[ean],
                                        ingredient_quantity=data['ean2quantity'][ean])
                    new_listing.save()
                if ean not in ean2form_data and ean in ean2listings:
                    ean2listings[ean].delete()

            update_recipe_cost(recipe)
            msg = {'success': 'Sucessfully updated recipe #%s: %s.' % (recipe_id, recipe.name)}
            return render(request, 'recipemanager/recipe_edit.html', msg)

    def delete(request, recipe_id):
        recipe = Recipe.objects.filter(id=recipe_id)[0]
        for l in RecipeListing.objects.filter(recipe=recipe):
            l.delete()
        recipe.delete()
        msg = {'success': 'Sucessfully deleted recipe #%s: %s.' % (recipe_id, recipe.name)}
        return render(request, 'recipemanager/recipe_edit.html', msg)

src/recipemanager/views.py
from django.http import HttpResponse
from .controllers import IngredientManager, RecipeManager, render_homepage


def index(request):
    return render_homepage(request)


def ingredient_list(request):
    return IngredientManager.list(request)


def ingredient_create(request):
    return IngredientManager.create(request)


def ingredient_edit(request, ingredient_id):
    return IngredientManager.edit(request, ingredient_id)


def ingredient_confirm_delete(request, ingredient_id):
    return IngredientManager.confirm_delete(request, ingredient_id)


def ingredient_delete(request, ingredient_id):
    return IngredientManager.delete(request, ingredient_id)


def recipe_list(request):
    return RecipeManager.list(request)


def recipe_create(request):
    return RecipeManager.create(request)


def recipe_view(request, recipe_id):
    return RecipeManager.view(request, recipe_id)


def recipe_edit(request, recipe_id):
    return RecipeManager.edit(request, recipe_id)


def recipe_delete(request, recipe_id):
    return RecipeManager.delete(request, recipe_id)

src/recipemanager/templates/recipemanager/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <!-- datatables -->
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">

        {% block head %} {% endblock %}

        <style>
        div {
            margin-bottom: 15px;
        }
        </style>

        <title> {% block title %} {% endblock %} </title>
    </head>
    <body>
        <div class="container">

            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="{% url 'recipemanager:index' %}">Recipe manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'recipemanager:ingredient_list'%}">ingredients</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'recipemanager:recipe_list'%}">recipes</a>
                        </li>
                    </ul>
                </div>
            </nav>

        </div>
        <div class="container">
            {% block body %} {% endblock %}
        </div>


        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <!-- datatables -->
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

        <script src="https://kit.fontawesome.com/e2cbf8229d.js" crossorigin="anonymous"></script>
        {% block scripts %} {% endblock %}
    </body>
</html>

src/recipemanager/templates/recipemanager/create.html
{% extends 'recipemanager/base.html' %}

{% block title %}
        Create ingredient
{% endblock %}


{% block body %}

<h1>create ingredient</h1>


{% if success %}
<div class="alert alert-success" role="alert">{{ success }}</div>
<a href="{% url 'recipemanager:ingredient_list' %}" class="btn btn-outline-primary btn-lg" role="button"
   aria-pressed="true">
    View ingredient list
</a>
<a href="{% url 'recipemanager:ingredient_create' %}" class="btn btn-outline-primary btn-lg" role="button"
   aria-pressed="true">
    Create another ingredient
</a>

{% else %}
    <form action="{% url 'recipemanager:ingredient_create' %}" method="post">
        {% csrf_token %}
        <div class="form-group form-row">
            <label for="ingredient-name">Name</label>
            <input name="name" type="text" class="form-control" id="ingredient-name" required
                   value="{{ form_data.name }}">
        </div>
        <div class="form-group form-row">
            <label for="ingredient-ean">EAN</label>
            <input name="ean" type="text" class="form-control" id="ingredient-ean" required
                   value="{{ form_data.ean}}">
        </div>
        <div class="form-group form-row">
            <div class="form-group">
                <label for="ingredient-amount">Item amount</label>
                <input name="amount" type="text" class="form-control" id="ingredient-amount"
                       required value="{{ form_data.amount}}">
            </div>
            <div class="form-group">
                <label for="ingredient-unit">Unit</label>
                <select name="unit" id="ingredient-unit" class="form-control"
                        value="{{form_data.unit}}">
                    <option selected>grams</option>
                    <option>kilograms</option>
                    <option>liter</option>
                    <option>centiliter</option>
                </select>
            </div>
        </div>
        <div class="form-group form-row">
            <label for="ingredient-price">Price (€)</label>
            <input name="price" type="text" class="form-control" id="ingredient-price"
                   required value="{{ form_data.price}}">
        </div>

        {% if error %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Error:</strong> {{ error }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}

        <button type="submit" class="btn btn-primary">save</button>
    </form>
{% endif %}

{% endblock %}

src/recipemanager/templates/recipemanager/home.html
{% extends 'recipemanager/base.html' %}
{% load static %}

{% block title %}Welcome{% endblock %}

{% block body %}
    <h1>Welcome to recipe manager!</h1>

    <a href="{% url 'recipemanager:ingredient_list' %}"
       class="btn btn-primary btn-lg"
       role="button"
       aria-pressed="true">
        Manage ingredients
    </a>

    <a href="{% url 'recipemanager:recipe_list' %}"
       class="btn btn-primary btn-lg"
       role="button"
       aria-pressed="true">
        Manage recipes
    </a>

{% endblock %}

src/recipemanager/templates/recipemanager/ingredient_confirm_delete.html
{% extends 'recipemanager/base.html' %}

{% block title %}
    Edit ingredient
{% endblock %}


{% block body %}

<h1>Warning</h1>

<div class="alert alert-warning" role="alert">
    <p>You are about to remove ingredient #{{ ingredient.ean }}: {{ ingredient.name }}.</p>

    {% if listings %}
        <p>The following recipes use this ingredients and will be affected:</p>
        {% for l in listings %}
            <p>- {{ l.recipe.name }}</p>
        {% endfor  %}
    {% endif %}

    <p>do you want to proceed?</p>
    <a href="{% url 'recipemanager:ingredient_delete' ingredient_id=ingredient.ean %}"
       class="btn btn-danger btn-lg"
       role="button"
       aria-pressed="true">
        yes
    </a>
    <a href="{% url 'recipemanager:ingredient_list' %}"
       class="btn btn-success btn-lg"
       role="button"
       aria-pressed="true">
       no
    </a>

</div>


<a href="{% url 'recipemanager:ingredient_list' %}"
   class="btn btn-outline-primary btn-lg"
   role="button"
   aria-pressed="true">
    View ingredient list
</a>

<a href="{% url 'recipemanager:ingredient_create' %}"
   class="btn btn-outline-primary btn-lg"
   role="button"
   aria-pressed="true">
    Create an ingredient
</a>

{% endblock %}

src/recipemanager/templates/recipemanager/ingredient_create.html
{% extends 'recipemanager/base.html' %}

{% block title %}
    Create ingredient
{% endblock %}


{% block body %}

<h1>create ingredient</h1>

{% include 'recipemanager/ingredient_form.html' %}

{% endblock %}

src/recipemanager/templates/recipemanager/ingredient_delete.html
{% extends 'recipemanager/base.html' %}

{% block title %}
    Edit ingredient
{% endblock %}


{% block body %}

<h1>Deleting ingredient</h1>

{% if success %}
    <div class="alert alert-success" role="alert">Ingredient deleted!</div>
{% else %}
    <div class="alert alert-danger" role="alert">
        Unable to delete ingredient with provided EAN.
    </div>
{% endif %}
    <a href="{% url 'recipemanager:ingredient_list' %}"
       class="btn btn-outline-primary btn-lg"
       role="button"
       aria-pressed="true">
        View ingredient list
    </a>
    <a href="{% url 'recipemanager:ingredient_create' %}"
       class="btn btn-outline-primary btn-lg"
       role="button"
       aria-pressed="true">
        Create an ingredient
    </a>
{% endblock %}

src/recipemanager/templates/recipemanager/ingredient_edit.html
{% extends 'recipemanager/base.html' %}

{% block title %}
    Edit ingredient
{% endblock %}


{% block body %}

<h1>Editing ingredient</h1>

{% if form_data or success %}
    {% include 'recipemanager/ingredient_form.html' %}

{% else %}
    <div class="alert alert-danger" role="alert">Unable to fetch ingredient with provided EAN.</div>
    <a href="{% url 'recipemanager:ingredient_list' %}" class="btn btn-outline-primary btn-lg" role="button"
       aria-pressed="true">
        View ingredient list
    </a>
    <a href="{% url 'recipemanager:ingredient_create' %}" class="btn btn-outline-primary btn-lg" role="button"
       aria-pressed="true">
        Create another ingredient
    </a>
{% endif %}


{% endblock %}

src/recipemanager/templates/recipemanager/ingredient_list.html
{% extends 'recipemanager/base.html' %}

{% block title %}
    List ingredients
{% endblock %}


{% block body %}

<div class="row">
    <h1>ingredients</h1>

    <a href="{% url 'recipemanager:ingredient_create' %}"
       class="btn btn-success btn-lg"
       role="button"
       aria-pressed="true">
        <i class="fa fa-plus-circle"></i>
    </a>
</div>

<table id="ingredients_tb" class="display">
    <thead>
        <tr>
            <th>Name</th>
            <th>EAN</th>
            <th>Amount</th>
            <th>Price</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for i in ingredients %}
            <tr>
                <td>{{ i.name }}</td>
                <td>{{ i.ean }}</td>
                <td>{{ i.amount }} {{ i.unit }}</td>
                <td>&euro; {{ i.price }}</td>
                <td>
                    <a href="{% url 'recipemanager:ingredient_edit' ingredient_id=i.ean %}">
                        <i class="fa fa-pencil"></i>
                    </a>
                </td>
                <td>
                    <a href="{% url 'recipemanager:ingredient_confirm_delete' ingredient_id=i.ean %}">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}
{% block scripts %}
<script>
    $(document).ready( function () {
        $('#ingredients_tb').DataTable();
    } );
</script>
{% endblock %}

src/recipemanager/templates/recipemanager/recipe_create.html
{% extends 'recipemanager/base.html' %}
{% load static %}

{% block title %}Create recipe{% endblock %}

{% block scripts %}
    {% include 'recipemanager/recipe_form.js' %}
{% endblock %}

{% block body %}
    <h1>create recipe</h1>
    {% include 'recipemanager/recipe_form.html' %}
{% endblock %}

src/recipemanager/templates/recipemanager/recipe_edit.html
{% extends 'recipemanager/base.html' %}

{% block title %}
    Edit
{% endblock %}

{% block scripts %}
    {% include 'recipemanager/recipe_form.js' %}
{% endblock %}

{% block body %}

<h1>Editing recipe</h1>

{% if form_data or success %}
    {% include 'recipemanager/recipe_form.html' %}

{% else %}
    <div class="alert alert-danger" role="alert">Unable to edit recipe.</div>
    <a href="{% url 'recipemanager:recipe' %}" class="btn btn-outline-primary btn-lg" role="button"
       aria-pressed="true">
        View recipe list
    </a>
    <a href="{% url 'recipemanager:recipe' %}" class="btn btn-outline-primary btn-lg" role="button"
       aria-pressed="true">
        Creat another recipe
    </a>
{% endif %}

{% endblock %}

src/recipemanager/templates/recipemanager/recipe_list.html
{% extends 'recipemanager/base.html' %}

{% block title %}
    List recipes
{% endblock %}


{% block body %}

<div class="row">
    <h1>Recipes</h1>

    <a href="{% url 'recipemanager:recipe_create' %}"
       class="btn btn-success btn-lg"
       role="button"
       aria-pressed="true">
        <r class="fa fa-plus-circle"></i>
    </a>
</div>

<table id="recipes_tb" class="display">
    <thead>
        <tr>
            <th>Name</th>
            <th>Cost</th>
            <th>View</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for r in recipes %}
            <tr>
                <td>{{ r.name }}</td>
                <td>&euro; {{ r.cost}}</td>
                <td>
                    <a href="{% url 'recipemanager:recipe_view' recipe_id=r.id%}">
                        <r class="fa fa-eye"></r>
                    </a>
                </td>
                <td>
                    <a href="{% url 'recipemanager:recipe_edit' recipe_id=r.id %}">
                        <r class="fa fa-pencil"></r>
                    </a>
                </td>
                <td>
                    <a href="{% url 'recipemanager:recipe_delete' recipe_id=r.id %}">
                        <r class="fa fa-trash"></r>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}
{% block scripts %}
<script>
    $(document).ready( function () {
        $('#recipes_tb').DataTable();
    } );
</script>
{% endblock %}

src/recipemanager/templates/recipemanager/recipe_view.html
{% extends 'recipemanager/base.html' %}
{% load static %}

{% block title %}View recipe{% endblock %}

{% block body %}
    <h1>{{ recipe.name }}</h1>
    <h2>&euro; {{ recipe.cost }}</h2>

    <a href="{% url 'recipemanager:recipe_edit' recipe_id=recipe.id%}"
       class="btn btn-primary btn-lg"
       role="button"
       aria-pressed="true">
        <r class="fa fa-pencil"></i>
    </a>

    <a href="{% url 'recipemanager:recipe_delete' recipe_id=recipe.id%}"
       class="btn btn-danger btn-lg"
       role="button"
       aria-pressed="true">
        <r class="fa fa-trash"></i>
    </a>

    <table id="recipe-listing" class="table">
        <thead class="thead-light">
            <th>EAN</th>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Unit cost</th>
        </thead>
        {% for l in listings %}
        <tr>
            <td>{{ l.ingredient.ean }}</td>
            <td>{{ l.ingredient.name }}</td>
            <td>&euro; {{ l.ingredient.price }} per {{ l.ingredient.amount }} {{ l.ingredient.unit }}</td>
            <td>{{ l.ingredient_quantity }} {{ l.ingredient.unit }}</td>
            <td>&euro; {{ l.unit_cost }}</td>
        </tr>
        {% endfor %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>Total: &euro; {{ recipe.cost }}</td>
        </tr>
    </table>


    <a href="{% url 'recipemanager:recipe_list' %}" class="btn btn-outline-primary btn-lg" role="button"
       aria-pressed="true">
        Return to recipes
    </a>



{% endblock %}